import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const siteDataSource = await readFile("lib/site-data.ts", "utf8");
const auditHistory = await readFile("lib/audit-history.ts", "utf8");
const postgres = await readFile("lib/postgres.ts", "utf8");
const pageViewTracker = await readFile("components/page-view-tracker.tsx", "utf8");
const pageViewRoute = await readFile("app/api/page-view/route.ts", "utf8");
const appShell = await readFile("components/app-shell.tsx", "utf8");
const globalsCss = await readFile("app/globals.css", "utf8");
const rankingDashboard = await readFile("components/ranking-dashboard.tsx", "utf8");
const stationAuditRunRoute = await readFile("app/api/station-audit/run/route.ts", "utf8");
const auditReportRoute = await readFile("app/api/audit-report/route.ts", "utf8");
const appStartup = await readFile("deploy/start-app.sh", "utf8");
const schedulerStartup = await readFile("deploy/start-scheduler.sh", "utf8");
const compose = await readFile("deploy/docker-compose.yml", "utf8");
const refreshCron = await readFile("deploy/cron/refresh.cron", "utf8");
const deployWorkflow = await readFile(".github/workflows/deploy-vps.yml", "utf8");

assert.match(siteDataSource, /return process\.env\.SITE_DATA_SOURCE\?\.trim\(\)\.toLowerCase\(\) \|\| "json"/);
assert.match(siteDataSource, /siteDataSource\(\) === "postgres" && hasDatabaseUrl\(\)/);
assert.doesNotMatch(siteDataSource, /if \(hasDatabaseUrl\(\)\) \{/);

assert.match(postgres, /from station_audit_runs/);
assert.match(postgres, /order by executed_at desc/);
assert.match(postgres, /from page_view_import_rows/);
assert.match(postgres, /from page_view_events/);
assert.match(pageViewTracker, /navigator\.sendBeacon/);
assert.match(pageViewTracker, /keepalive: true/);
assert.match(pageViewTracker, /lastSentPath === pathname/);
assert.match(pageViewRoute, /PAGE_VIEW_TRACKING_ENABLED !== "0"/);
assert.match(pageViewRoute, /normalizePageViewPath\(path\)/);
assert.match(pageViewRoute, /recordPageViewEvent\(normalized\)/);
assert.match(pageViewRoute, /revalidatePath\(normalized\.canonicalPath\)/);
assert.match(pageViewRoute, /if \(normalized\.canonicalPath === "\/ranking"\)/);
assert.match(pageViewRoute, /revalidatePath\("\/"\)/);
assert.match(appShell, /const copyrightYear = new Date\(\)\.getFullYear\(\)/);
assert.match(appShell, /Copyright © \{copyrightYear\} ttop5\. All rights reserved\./);
assert.match(appShell, /className="page-footer-line"/);
assert.match(globalsCss, /\.page-footer\s*\{[\s\S]*text-align:\s*center/);
const compareByModeBody = rankingDashboard.match(/function compareByMode[\s\S]*?\n}\r?\n/)?.[0] ?? "";
assert.doesNotMatch(compareByModeBody, /pageViews|pv|PV/);
assert.doesNotMatch(rankingDashboard, /pageViews\.stationPv|pageViews[\s\S]{0,80}\.sort|sort[\s\S]{0,80}pageViews/);
assert.match(auditHistory, /siteDataSource\(\) === "postgres" && hasDatabaseUrl\(\)/);
assert.match(auditHistory, /readStationAuditRunRows\(\)/);
assert.match(auditHistory, /parseAuditHistorySearchParams/);
assert.match(auditHistory, /getAuditHistoryPage/);
assert.match(auditHistory, /readStationAuditRunPage\(query\)/);
assert.match(auditHistory, /SITE_DATA_ALLOW_FILE_FALLBACK === "1"/);
assert.match(auditHistory, /throw error/);
assert.match(postgres, /readStationAuditRunPage/);
assert.match(postgres, /limit \$\$\{limitParam\}/);
assert.match(postgres, /offset \$\$\{offsetParam\}/);
assert.match(stationAuditRunRoute, /postgresSiteDataEnabled\(\)/);
assert.match(stationAuditRunRoute, /\["scripts\/publish_site_data_snapshot\.py", "--source", "station-audit-run"\]/);
assert.match(stationAuditRunRoute, /\["scripts\/publish_audit_history\.py", "--delete-missing"\]/);
assert.match(stationAuditRunRoute, /const AUDIT_RATE_LIMIT = 4/);
assert.match(stationAuditRunRoute, /const MODEL_PROBE_RATE_LIMIT = 20/);
assert.match(stationAuditRunRoute, /checkRateLimit\(`audit:\$\{ip\}`/);
assert.match(stationAuditRunRoute, /checkRateLimit\(`model-probe:\$\{ip\}`/);
assert.match(stationAuditRunRoute, /assertPublicAuditTarget\(apiBaseUrl\)/);
assert.match(stationAuditRunRoute, /\`\$\{base\}\/models\`/);
assert.match(stationAuditRunRoute, /\`\$\{base\}\/v1\/models\`/);
assert.match(stationAuditRunRoute, /authorization: `Bearer \$\{apiKey\}`/);
assert.match(stationAuditRunRoute, /"x-api-key": apiKey/);
assert.match(stationAuditRunRoute, /sanitizeEventValue\(payload, secrets\)/);
assert.match(stationAuditRunRoute, /suggestedModels: probe\.models\.slice\(0, 8\)/);
assert.match(stationAuditRunRoute, /422/);
assert.match(auditReportRoute, /resolveAuditRunReportPath\(stationKey, model, runId\)/);
assert.match(auditHistory, /const AUDIT_SEGMENT_PATTERN = \/\^\[A-Za-z0-9\._-\]\+\$\//);
assert.match(auditHistory, /filePath\.startsWith\(root \+ path\.sep\)/);
assert.match(auditHistory, /normalizeDetectorResult/);
assert.match(auditHistory, /criticalFindings/);
assert.match(appStartup, /\[ "\$\{SITE_DATA_SOURCE:-json\}" = "postgres" \]/);
assert.match(schedulerStartup, /\[ "\$\{SITE_DATA_SOURCE:-json\}" = "postgres" \]/);
assert.match(appStartup, /python scripts\/publish_audit_history\.py --delete-missing/);
assert.match(schedulerStartup, /python scripts\/publish_audit_history\.py --delete-missing/);
assert.match(compose, /SITE_DATA_SOURCE: \$\{SITE_DATA_SOURCE:-postgres\}/);
assert.match(compose, /SITE_DATA_MERGE_POSTGRES_BASE: \$\{SITE_DATA_MERGE_POSTGRES_BASE:-1\}/);
assert.match(compose, /DATABASE_URL: postgresql:\/\/\$\{POSTGRES_USER\}:\$\{POSTGRES_PASSWORD\}@postgres:5432\/\$\{POSTGRES_DB\}/);
assert.match(refreshCron, /python scripts\/run_server_refresh\.py/);
assert.doesNotMatch(refreshCron, /SITE_DATA_SOURCE/);
assert.match(deployWorkflow, /Create pre-deploy backup/);
assert.match(deployWorkflow, /pg_dump -U api_relay_rank -d api_relay_rank -Fc/);
assert.match(deployWorkflow, /EXPECTED_AUDIT_RUNS/);
assert.match(deployWorkflow, /Verify deployed site data/);
assert.match(deployWorkflow, /select count\(\*\) from station_audit_runs/);
assert.match(deployWorkflow, /schema_migrations where version = 3/);
assert.match(deployWorkflow, /site_data_snapshots where status='success'/);
assert.match(deployWorkflow, /\/api\/audit-report/);

console.log("site and audit data only use PostgreSQL when SITE_DATA_SOURCE=postgres.");
