import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const siteDataSource = await readFile("lib/site-data.ts", "utf8");
const auditHistory = await readFile("lib/audit-history.ts", "utf8");
const postgres = await readFile("lib/postgres.ts", "utf8");
const pageViewTracker = await readFile("components/page-view-tracker.tsx", "utf8");
const pageViewRoute = await readFile("app/api/page-view/route.ts", "utf8");
const appShell = await readFile("components/app-shell.tsx", "utf8");
const globalsCss = await readFile("app/globals.css", "utf8");
const rankingDashboard = await readFile("components/ranking-dashboard.tsx", "utf8");
const stationFeedbackPanel = await readFile("components/station-feedback-panel.tsx", "utf8");
const siteDataView = await readFile("lib/site-data-view.ts", "utf8");
const stationDetailPage = await readFile("app/stations/[station]/page.tsx", "utf8");
const stationReviewRoute = await readFile("app/api/station-reviews/route.ts", "utf8");
const stationErrorReportRoute = await readFile("app/api/station-error-reports/route.ts", "utf8");
const stationAuditRunRoute = await readFile("app/api/station-audit/run/route.ts", "utf8");
const auditReportRoute = await readFile("app/api/audit-report/route.ts", "utf8");
const auditHistoryTable = await readFile("components/audit-history-table.tsx", "utf8");
const userFeedback = await readFile("lib/user-feedback.ts", "utf8");
const appStartup = await readFile("deploy/start-app.sh", "utf8");
const schedulerStartup = await readFile("deploy/start-scheduler.sh", "utf8");
const compose = await readFile("deploy/docker-compose.yml", "utf8");
const refreshCron = await readFile("deploy/cron/refresh.cron", "utf8");
const deployWorkflow = await readFile(".github/workflows/deploy-vps.yml", "utf8");
const databaseScript = await readFile("scripts/database.py", "utf8");
const gitignore = await readFile(".gitignore", "utf8");
const dockerignore = await readFile(".dockerignore", "utf8");

assert.match(siteDataSource, /return process\.env\.SITE_DATA_SOURCE\?\.trim\(\)\.toLowerCase\(\) \|\| "json"/);
assert.match(siteDataSource, /siteDataSource\(\) === "postgres" && hasDatabaseUrl\(\)/);
assert.doesNotMatch(siteDataSource, /if \(hasDatabaseUrl\(\)\) \{/);

assert.match(postgres, /from station_audit_runs/);
assert.match(postgres, /order by executed_at desc/);
assert.match(postgres, /from page_view_import_rows/);
assert.match(postgres, /from page_view_events/);
assert.match(pageViewTracker, /navigator\.sendBeacon/);
assert.match(pageViewTracker, /keepalive: true/);
assert.match(pageViewTracker, /lastSentPath === pathname/);
assert.match(pageViewRoute, /PAGE_VIEW_TRACKING_ENABLED !== "0"/);
assert.match(pageViewRoute, /normalizePageViewPath\(path\)/);
assert.match(pageViewRoute, /recordPageViewEvent\(normalized\)/);
assert.match(pageViewRoute, /revalidatePath\(normalized\.canonicalPath\)/);
assert.match(pageViewRoute, /if \(normalized\.canonicalPath === "\/ranking"\)/);
assert.match(pageViewRoute, /revalidatePath\("\/"\)/);
assert.match(appShell, /const copyrightYear = new Date\(\)\.getFullYear\(\)/);
assert.match(appShell, /Copyright © \{copyrightYear\} ttop5\. All rights reserved\./);
assert.match(appShell, /className="page-footer-line"/);
assert.match(globalsCss, /\.page-footer\s*\{[\s\S]*text-align:\s*center/);
const compareByModeBody = rankingDashboard.match(/function compareByMode[\s\S]*?\n}\r?\n/)?.[0] ?? "";
assert.doesNotMatch(compareByModeBody, /pageViews|pv|PV/);
assert.match(compareByModeBody, /mode === "review_rating"/);
assert.match(compareByModeBody, /reviewAverageRating/);
assert.match(compareByModeBody, /reviewCount/);
assert.doesNotMatch(rankingDashboard, /pageViews\.stationPv|pageViews[\s\S]{0,80}\.sort|sort[\s\S]{0,80}pageViews/);
assert.match(rankingDashboard, /value: "review_rating", label: "用户评分优先"/);
assert.match(rankingDashboard, /用户评分/);
assert.match(rankingDashboard, /href=\{`\/stations\/\$\{stationKey\}#reviews`\}/);
assert.match(rankingDashboard, /className=\{hasReviewScore \? "ranking-review-summary" : "ranking-review-summary ranking-review-empty"\}/);
assert.doesNotMatch(rankingDashboard, /倍率口径/);
const mobileStationCardBody = rankingDashboard.match(/function MobileStationCard[\s\S]*?\n}\r?\n\r?\nexport function RankingDashboard/)?.[0] ?? "";
assert.match(mobileStationCardBody, /MobileMetric label="用户评价"/);
assert.doesNotMatch(mobileStationCardBody, /<details className="mobile-card-details" open>/);
assert.match(siteDataView, /reviewAverageRating/);
assert.match(siteDataView, /reviewCount/);
assert.match(siteDataView, /reviewSummaries\[station\.key\]/);
assert.match(globalsCss, /\.registry-table \.registry-col-review/);
assert.match(stationReviewRoute, /searchParams\.get\("limit"\)/);
assert.match(stationReviewRoute, /searchParams\.get\("offset"\)/);
assert.match(stationReviewRoute, /readStationReviewPage\(stationKey, viewer\?\.githubId, \{ limit, offset \}\)/);
assert.match(stationReviewRoute, /Rating must be one of 2, 4, 6, 8, 10\./);
assert.match(postgres, /limit \+ 1/);
assert.match(postgres, /offset \$3/);
assert.match(userFeedback, /ERROR_REPORT_CATEGORIES[\s\S]*\[\s*\{ value: "station_url", label: "站点地址" \}/);
assert.match(userFeedback, /\{ value: "other", label: "其他错误" \}/);
assert.match(userFeedback, /REVIEW_RATING_CHOICES/);
assert.match(userFeedback, /\{ stars: 1, rating: 2, label: "很差" \}/);
assert.match(userFeedback, /\{ stars: 2, rating: 4, label: "较差" \}/);
assert.match(userFeedback, /\{ stars: 3, rating: 6, label: "还行" \}/);
assert.match(userFeedback, /\{ stars: 4, rating: 8, label: "推荐" \}/);
assert.match(userFeedback, /\{ stars: 5, rating: 10, label: "力荐" \}/);
assert.match(userFeedback, /REVIEW_RATING_VALUES\.has\(rating as 2 \| 4 \| 6 \| 8 \| 10\)/);
assert.match(userFeedback, /ratingToStars/);
assert.match(userFeedback, /ratingLabel/);
assert.match(userFeedback, /averageRating\.toFixed\(1\)} 分 \/ \$\{summary\.reviewCount\} 条/);
assert.match(stationFeedbackPanel, /role="dialog"/);
assert.match(stationFeedbackPanel, /onMouseDown=\{onClose\}/);
assert.match(stationFeedbackPanel, /<section id="reviews" className="section feedback-review-section">/);
assert.match(stationFeedbackPanel, /加载更多/);
assert.match(stationFeedbackPanel, /错误上报已提交，感谢您的反馈，我们会在周末统一汇总处理。/);
assert.match(stationFeedbackPanel, /REVIEW_RATING_CHOICES\.map/);
assert.match(stationFeedbackPanel, /feedback-star-rating/);
assert.match(stationFeedbackPanel, /ratingToStars\(rating\)/);
assert.match(stationFeedbackPanel, /请选择评分。/);
assert.match(stationFeedbackPanel, /ratingLabel\(review\.rating\)/);
assert.match(stationFeedbackPanel, /选择 1-5 星（10 分制）/);
assert.match(stationFeedbackPanel, /Loader2/);
assert.match(stationFeedbackPanel, /className="spin-icon"/);
assert.match(stationFeedbackPanel, /authChecking/);
assert.match(stationFeedbackPanel, /setAuthChecking\(true\)/);
assert.match(stationFeedbackPanel, /fetchReviewPage\(0\)/);
assert.match(stationFeedbackPanel, /正在检查登录状态/);
assert.match(stationFeedbackPanel, /提交中/);
assert.match(stationFeedbackPanel, /保存中/);
assert.match(stationFeedbackPanel, /刷新中/);
assert.match(stationFeedbackPanel, /加载中/);
assert.doesNotMatch(stationFeedbackPanel, /RATING_OPTIONS/);
assert.doesNotMatch(stationFeedbackPanel, /feedback-rating-option/);
assert.match(stationFeedbackPanel, /StationFeedbackActions/);
assert.match(stationFeedbackPanel, /StationReviewSection/);
assert.doesNotMatch(stationFeedbackPanel, /feedback-grid/);
assert.doesNotMatch(stationFeedbackPanel, /className="section feedback-section"/);
assert.match(stationErrorReportRoute, /const MAX_REPORTS_PER_USER_PER_WEEK = 10/);
assert.match(stationErrorReportRoute, /const WEEKLY_REPORT_LIMIT_WINDOW_MS = 7 \* DAY_MS/);
assert.match(stationErrorReportRoute, /weeklyRecent\.total >= MAX_REPORTS_PER_USER_PER_WEEK/);
assert.match(stationErrorReportRoute, /近 7 天错误上报次数已达上限/);
assert.match(stationDetailPage, /StationFeedbackProvider/);
assert.match(stationDetailPage, /StationFeedbackActions/);
assert.match(stationDetailPage, /StationReviewSection/);
assert.match(stationDetailPage, /readStationReviewPage\(rawStation\.key, null\)/);
assert.doesNotMatch(stationDetailPage, /getAuthenticatedGithubUser/);
assert.doesNotMatch(stationDetailPage, /<StationFeedbackPanel/);
assert.match(globalsCss, /\.ranking-review-summary:hover/);
assert.match(globalsCss, /\.feedback-review-section\s*\{[\s\S]*scroll-margin-top:\s*88px/);
assert.match(auditHistory, /siteDataSource\(\) === "postgres" && hasDatabaseUrl\(\)/);
assert.match(auditHistory, /readStationAuditRunRows\(\)/);
assert.match(auditHistory, /parseAuditHistorySearchParams/);
assert.match(auditHistory, /getAuditHistoryPage/);
assert.match(auditHistory, /readStationAuditRunPage\(query\)/);
assert.match(auditHistory, /SITE_DATA_ALLOW_FILE_FALLBACK === "1"/);
assert.match(auditHistory, /throw error/);
assert.match(auditHistoryTable, /Loader2/);
assert.match(auditHistoryTable, /pendingControl/);
assert.match(auditHistoryTable, /type AuditPendingControl/);
assert.match(auditHistoryTable, /disabled=\{isPending\}/);
assert.match(auditHistoryTable, /loading=\{isPending && pendingControl === `sort:\$\{key\}`\}/);
assert.match(auditHistoryTable, /audit-history-loading-note/);
assert.match(auditHistoryTable, /loading=\{isPending && pendingControl === "page:next"\}/);
assert.match(auditHistoryTable, /updateQuery\(\{ pageSize: Number\(event\.target\.value\) \}, "page:size"\)/);
assert.match(globalsCss, /\.audit-history-sort-button:disabled/);
assert.match(globalsCss, /\.audit-history-loading-note/);
assert.match(postgres, /readStationAuditRunPage/);
assert.match(postgres, /limit \$\$\{limitParam\}/);
assert.match(postgres, /offset \$\$\{offsetParam\}/);
assert.match(stationAuditRunRoute, /postgresSiteDataEnabled\(\)/);
assert.match(stationAuditRunRoute, /\["scripts\/publish_site_data_snapshot\.py", "--source", "station-audit-run"\]/);
assert.match(stationAuditRunRoute, /\["scripts\/publish_audit_history\.py", "--delete-missing"\]/);
assert.match(stationAuditRunRoute, /const AUDIT_RATE_LIMIT = 4/);
assert.match(stationAuditRunRoute, /const MODEL_PROBE_RATE_LIMIT = 20/);
assert.match(stationAuditRunRoute, /checkRateLimit\(`audit:\$\{ip\}`/);
assert.match(stationAuditRunRoute, /checkRateLimit\(`model-probe:\$\{ip\}`/);
assert.match(stationAuditRunRoute, /assertPublicAuditTarget\(apiBaseUrl\)/);
assert.match(stationAuditRunRoute, /\`\$\{base\}\/models\`/);
assert.match(stationAuditRunRoute, /\`\$\{base\}\/v1\/models\`/);
assert.match(stationAuditRunRoute, /authorization: `Bearer \$\{apiKey\}`/);
assert.match(stationAuditRunRoute, /"x-api-key": apiKey/);
assert.match(stationAuditRunRoute, /sanitizeEventValue\(payload, secrets\)/);
assert.match(stationAuditRunRoute, /suggestedModels: probe\.models\.slice\(0, 8\)/);
assert.match(stationAuditRunRoute, /422/);
assert.match(auditReportRoute, /resolveAuditRunReportPath\(stationKey, model, runId\)/);
assert.match(auditHistory, /const AUDIT_SEGMENT_PATTERN = \/\^\[A-Za-z0-9\._-\]\+\$\//);
assert.match(auditHistory, /filePath\.startsWith\(root \+ path\.sep\)/);
assert.match(auditHistory, /normalizeDetectorResult/);
assert.match(auditHistory, /criticalFindings/);
assert.match(appStartup, /\[ "\$\{SITE_DATA_SOURCE:-json\}" = "postgres" \]/);
assert.match(schedulerStartup, /\[ "\$\{SITE_DATA_SOURCE:-json\}" = "postgres" \]/);
assert.match(appStartup, /python scripts\/publish_audit_history\.py --delete-missing/);
assert.match(schedulerStartup, /python scripts\/publish_audit_history\.py --delete-missing/);
assert.match(compose, /SITE_DATA_SOURCE: \$\{SITE_DATA_SOURCE:-postgres\}/);
assert.match(compose, /SITE_DATA_MERGE_POSTGRES_BASE: \$\{SITE_DATA_MERGE_POSTGRES_BASE:-1\}/);
assert.match(compose, /DATABASE_URL: postgresql:\/\/\$\{POSTGRES_USER\}:\$\{POSTGRES_PASSWORD\}@postgres:5432\/\$\{POSTGRES_DB\}/);
assert.match(gitignore, /data\/_user_uploads\//);
assert.match(dockerignore, /data\/_user_uploads/);
assert.match(refreshCron, /python scripts\/run_server_refresh\.py/);
assert.match(refreshCron, /0 22 \* \* 5 cd \/app && python scripts\/send_weekly_error_report_digest\.py/);
assert.doesNotMatch(refreshCron, /SITE_DATA_SOURCE/);
assert.match(databaseScript, /MIGRATION_VERSION = 7/);
assert.match(databaseScript, /create table if not exists station_reviews/);
assert.match(databaseScript, /unique \(station_key, github_id\)/);
assert.match(databaseScript, /rating smallint not null constraint station_reviews_rating_check check \(rating in \(2, 4, 6, 8, 10\)\)/);
assert.match(databaseScript, /def apply_schema_migrations/);
assert.doesNotMatch(databaseScript, /delete from station_reviews/);
assert.doesNotMatch(databaseScript, /delete from station_reviews where rating = 4/);
assert.match(databaseScript, /station_reviews_rating_check check \(rating in \(2, 4, 6, 8, 10\)\)/);
assert.match(databaseScript, /station_error_reports_category_check check \(category in \('station_url', 'group_multiplier', 'recharge_tier', 'announcement', 'ranking_metric', 'other'\)\)/);
assert.match(databaseScript, /insert into schema_migrations \(version\) values \(5\)/);
assert.match(databaseScript, /insert into schema_migrations \(version\) values \(6\)/);
assert.match(databaseScript, /insert into schema_migrations \(version\) values \(7\)/);
assert.match(deployWorkflow, /Create pre-deploy backup/);
assert.match(deployWorkflow, /pg_dump -U api_relay_rank -d api_relay_rank -Fc/);
assert.match(deployWorkflow, /EXPECTED_AUDIT_RUNS/);
assert.match(deployWorkflow, /Verify deployed site data/);
assert.match(deployWorkflow, /Configure user feedback secrets on VPS/);
assert.match(deployWorkflow, /AUTH_GITHUB_ID/);
assert.match(deployWorkflow, /AUTH_GITHUB_SECRET/);
assert.match(deployWorkflow, /secret is required for user feedback deployment/);
assert.match(deployWorkflow, /\/api\/auth\/providers/);
assert.match(deployWorkflow, /github=payload\.get\("github"\)/);
assert.match(deployWorkflow, /expected_github_callback="\$site_url\/api\/auth\/callback\/github"/);
assert.match(deployWorkflow, /\/api\/auth\/csrf/);
assert.match(deployWorkflow, /\/api\/auth\/signin\/github/);
assert.match(deployWorkflow, /github_authorize_url/);
assert.match(deployWorkflow, /test -n "\$github_authorize_url"/);
assert.match(deployWorkflow, /same_origin_status/);
assert.match(deployWorkflow, /Origin: \$site_url/);
assert.match(deployWorkflow, /test "\$same_origin_status" = "401"/);
assert.match(deployWorkflow, /cross_origin_status/);
assert.match(deployWorkflow, /Origin: https:\/\/evil\.example/);
assert.match(deployWorkflow, /test "\$cross_origin_status" = "403"/);
assert.match(deployWorkflow, /select count\(\*\) from station_audit_runs/);
assert.match(deployWorkflow, /schema_migrations where version = 7/);
assert.match(deployWorkflow, /schema_migrations version 7 is missing/);
assert.match(deployWorkflow, /site_data_snapshots where status='success'/);
assert.match(deployWorkflow, /\/api\/audit-report/);
assert.match(deployWorkflow, /PRE_DEPLOY_STATION_COUNT/);
assert.match(deployWorkflow, /pre-deploy-station-count\.txt/);
assert.match(deployWorkflow, /ALLOW_SITE_DATA_STATION_COUNT_DROP/);
assert.match(deployWorkflow, /Deployed station count dropped from/);

console.log("site and audit data only use PostgreSQL when SITE_DATA_SOURCE=postgres.");
